#!/usr/bin/python -v
# EASY-INSTALL-ENTRY-SCRIPT: 'csvkit==0.9.1','console_scripts','csvlook'
__requires__ = 'csvkit==0.9.1'
import sys
from pkg_resources import load_entry_point

sys.exit(
   load_entry_point('csvkit==0.9.1', 'console_scripts', 'csvlook')()
)
